octeontx2-pf: fix -Wdeclaration-after-statement warning in otx2_open
Fix follwing build warning:
 drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c: In function 'otx2_open':
| drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c:2129:17:
    error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
|  2129 |                 int name_len;
|       |                 ^~~

Fixes: 6631025d3179 ("octeontx2-pf: Treat truncation of IRQ name as an error")
Signed-off-by: Rui He <rui.he@windriver.com>