octeontx-83: fix build warning
Fix build warning:
drivers/net/ethernet/cavium/thunder/thunder_bgx.c:286:22: error:
unused variable 'lmac' [-Werror=unused-variable]

Signed-off-by: Rui He <rui.he@windriver.com>