octeontx-83: fix unused variable warning in thunder_bgx.c
Fixed following compilation warning.
    drivers/net/ethernet/cavium/thunder/thunder_bgx.c:
      In function 'bgx_set_lmac_mac':
  | drivers/net/ethernet/cavium/thunder/thunder_bgx.c:286:22:
      error: unused variable 'lmac' [-Werror=unused-variable]
  |   286 |         struct lmac *lmac = &bgx->lmac[lmacid];
  |       |                      ^~~~

Fixes: 35e471453d6a ("net: thunderx: update dmac filter when user changes mac addr")
Signed-off-by: Rui He <rui.he@windriver.com>